version: 4.6.0.{build}

#Publish to PowerShell Gallery with this key
environment:
  my_variable:
    secure: 59ZslplLCHq0faY9FOimdtrUqjJdxPYHsbgtedVpAlLE7Uiw1aoQqPn12CVFAX3y
    
image: WMF 5
skip_commits:
  message: /updated readme.*|update readme.*s/
build: off

before_test:
  - echo script1
  - ps: ./build/dotnet-install.ps1

test_script:
  - ps: ./build.ps1